apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: go-observe-cockroachdb
spec:
  groups:
  - name: go-observe-cockroachdb.rules
    rules:
    # Borrowed from https://landing.google.com/sre/workbook/chapters/alerting-on-slos/
    - record: job:slo_errors_per_request:ratio_rate10m
      expr: sum(rate(fake_http_request_count{namespace="{{ .Release.Namespace }}",code!="200"}[10m])) / sum(rate(fake_http_request_count{namespace="{{ .Release.Namespace }}"}[10m]))     
  - name: rick_johnson-alert.rules
    rules:
    - record: job:slo_errors_per_request:ratio_rate5m
      expr: sum(rate(fake_http_request_count{namespace="{{ .Release.Namespace }}",code!="200"}[5m])) / sum(rate(fake_http_request_count{namespace="{{ .Release.Namespace }}"}[5m]))
    - alert: ricks slo_errors above capacity
      expr: job:slo_errors_per_request:ratio_rate5m > 0.5     